### ISSUE TITLE
Why we have `remove_securityContext` in openshift.py

### ISSUE THREAD

**Issue by surajssd** [projectatomic/openshift2nulecule#10]
Why do we have this function [`remove_securityContext`](https://github.com/projectatomic/openshift2nulecule/blob/master/openshift2nulecule/openshift.py#L150)? `artifacts = oc.remove_securityContext(artifacts)` is being called from [here](https://github.com/projectatomic/openshift2nulecule/blob/master/openshift2nulecule/cli/main.py#L78).
What I mean here is that in [`export_all`](https://github.com/projectatomic/openshift2nulecule/blob/master/openshift2nulecule/openshift.py#L121) we don't export pods for now! 

Right now we only fetch data of [`["replicationcontrollers", "persistentvolumeclaims", "services"]`](https://github.com/projectatomic/openshift2nulecule/blob/master/openshift2nulecule/openshift.py#L130) in `export_all`.

So we may not get the data about pods, so unless I run 
`oc --namespace some-random-project export pods -o json` I will not get pods data.

If we are not getting data about pods we may not need funciton that removes data about pods.

**Comment by kadel** [comment]
`remove_securityContext` is hack and it is only mend Kubernetes artifacts.

This is also reason for exporting only RC, PVC, and SVC. 
Because not all object that are in OpenShift are also in Kubernetes, for first prototype I only chose those three. This is not great solution because we definitely need export more things, but this was first easy way how to get started. 

> If we are not getting data about pods we may not need funciton that removes data about pods.
You are right, that right now this function has no use. It is wrong that we are not exporting Pods, and we should do that.

**Comment by kadel** [comment]
closing, because we don't do that anymore, as we don't export  pods #53
