### ISSUE TITLE
Use `which` and `subprocess` to find the location of `oc`

### ISSUE THREAD

**Issue by surajssd** [projectatomic/openshift2nulecule#11]
In function [`_find_oc`](https://github.com/projectatomic/openshift2nulecule/blob/master/openshift2nulecule/openshift.py#L35) (which helps us find location of `oc` binary), what I suggest here is we can use python module `subprocess` and `linux` binary `which` to find the location of `oc` binary.

Something like this:
`subprocess.check_output(['which', 'oc']).strip()`

Rather than manually looking in the paths it is installed.

**Comment by kadel** [comment]
I do manual looking because when this is run in Docker container.
I didn't want to put `oc` binary to container, instead I choose to mount whole root of host system to container as `/host` and use `oc` from host. `oc` is then somewhere in `/host` (probably in `/usr/bin/` or `/usr/local/bin`) and in that case `which` is not going to help :-( 

But now when I'm thinking about it in same commit I also added detection if program is running inside container or not.
So when we are not in container we can use `which` or even just call `oc` (so it searches $PATH)

good catch @surajssd :+1: :wink:

**Comment by surajssd** [comment]
@kadel `which` fails in container, so the way it is being done seems good!

**Comment by kadel** [comment]
I'm going to close this. We can revisit this if current solution starting to be problematic.
